### ISSUE TITLE
is Touchy.js definitely robust enough?

### ISSUE THREAD

**Issue by dmalan** [cs50/draw50#5]
Noticed it's not been updated for 6 years, https://github.com/jairajs89/Touchy.js.

**Comment by dcoffey3296** [comment]
It's a good question, has 1K+ stars, 75 forks, only 3 open issues.  Old code base but will require further testing.

**Comment by dcoffey3296** [comment]
@rongxin-liu found hammer.js which is more robust.  Still has some quirks on the surface hub hardware especially, but basic functionality is rock-solid.
